nginx-ingress:
  controller:
    image:
      tag: 0.9.0-beta.7
    service:
      type: ClusterIP

kube-lego:
  config:
    LEGO_EMAIL: ds-instr@berkeley.edu
    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
  
